=== vyctorhff/books/LivroXML/src/Xml/exercicio/ExecVideo.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!--
            Document   : ExecVideo.dtd
            Created on : 16 de Dezembro de 2005, 21:02
            Author     : Victor Hugo
            Description:
                Purpose of the document follows.

            TODO define vocabulary identification data
            PUBLIC ID  : -//vendor//vocabulary//EN
            SYSTEM ID  : http://server/path/ExecVideo.dtd
        -->

        <!-- TODO define your own vocabulary/syntax. Example follows:  -->
        <!ELEMENT database (livro)+>

        <!ENTITY HD "Havery Deitel">
        <!ENTITY PD "Paul Deitel">
        <!ENTITY TN "Tem Nieto">

        <!ENTITY % CH "(capitulo, descricao)">

        <!ELEMENT livro (autor+, imagme*, conteudo, novocapitolo*)>
        <!ATTLIST livro livroID ID #REQUIRED>

        <!ELEMENT autor (#PCDATA)>

        <!ELEMENT imagem (#PCDATA)>

        <!ELEMENT conteudo %CH;>

        <!ELEMENT novocapitolo %CH;>
        <!ATTLIST novocapitolo added (true | false) "false">

        <!ELEMENT capitolo (#PCDATA)>
        <!ATTLIST capitolo numero CDATA #REQUIRED>

        <!ELEMENT descricao (secao*, revisao*, sumario?)>

        <!ELEMENT secao (#PCDATA)>

        <!ELEMENT revisao (#PCDATA)>

        <!ELEMENT sumario (#PCDATA)>

=== vyctorhff/books/LivroXML/src/Xml/exercicio/ExecVideo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : ExecVideo.xml
    Created on : 16 de Dezembro de 2005, 21:14
    Author     : Victor Hugo
    Description:
        Testa esta de acordo com o dtd ExecVideo do livro
-->
<!DOCTYPE ExecVideo SYSTEM "ExecVideo.dtd">
<database>
    <livro livroID="1">
        <autor>Fulano</autor>
        <imagem>Nada</imagem>
        <conteudo>
            <capitolo>2</capitolo>
            <descricao>
                <secao>8</secao>
                <revisao>beltrano</revisao>
                <sumario>seila</sumario>
            </descricao>
        </conteudo>
        <novocapitolo>
            <capitolo>5</capitolo>
            <descricao>
                <secao>7</secao>
                <revisao>Cicrano</revisao>
                <sumario>coisa e tal</sumario>
            </descricao>
        </novocapitolo>
    </livro>
</database>
